namespace GenerateSubjectLists
{
    internal static class BragiProcessor
    {
        /// <summary>
        /// Reads the subjects file, splits into discipline lists, writes all output files.
        /// </summary>
        /// <param name="inputSubjectsFile">Full path to Subjects.txt</param>
        /// <param name="uncategorizedOutputFile">Full path where uncategorized subjects will be written</param>
        /// <param name="outputFolder">Folder where all discipline subject files will be written</param>
        public static void GenerateSubjectLists(string inputSubjectsFile, string uncategorizedOutputFile, string outputFolder)
        {
            // Read in the file containing the file 
            string contents = File.ReadAllText(inputSubjectsFile);
            IEnumerable<string> ContentArray = contents.Split("\r\n");

            // Sort into the string enumerables to create lists in Email NewBooks
            IEnumerable<string> art = ContentArray.Where(x => (x.ToString().ToLower().Contains("art", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("artist", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("painting", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> biology = ContentArray.Where(x => (x.ToString().ToLower().Contains("biology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("botany", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("ecology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("microbiology", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> business = ContentArray.Where(x => (x.ToString().ToLower().Contains("business", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("economy", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("economic", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("accounting", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("accountant", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("advertising", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("management", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> chemistry = ContentArray.Where(x => (x.ToString().ToLower().Contains("chemistry", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("chemical", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("chemist", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> computer = ContentArray.Where(x => (x.ToString().ToLower().Contains("computer", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("information technology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("technology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("coding", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> education = ContentArray.Where(x => x.ToString().ToLower().Contains("education", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("teaching", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("teachers", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("learning", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("history", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("picture book", StringComparison.CurrentCulture));
            IEnumerable<string> fiction = ContentArray.Where(x => x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture));
            IEnumerable<string> forensics = ContentArray.Where(x => (x.ToString().ToLower().Contains("forensics", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("crime", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("crimin", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("criminology", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> geoscience = ContentArray.Where(x => (x.ToString().ToLower().Contains("geology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("hydrology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("tectonics", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("topographic", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> history = ContentArray.Where(x => (x.ToString().ToLower().Contains("history", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("biography", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("autobiography", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("social", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> hper = ContentArray.Where(x => (x.ToString().ToLower().Contains("health", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("exercise", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("athlete", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("athletic", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> humanities = ContentArray.Where(x => (x.ToString().ToLower().Contains("language", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("literature", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> idt = ContentArray.Where(x => x.ToString().ToLower().Contains("instructional design", StringComparison.CurrentCulture) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> inter = ContentArray.Where(x => (x.ToString().ToLower().Contains("geneder", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("sexuality", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("ethnology", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("sociology", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> math = ContentArray.Where(x => (x.ToString().ToLower().Contains("math", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("trigonometry", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("linear algebra", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("calculus", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("geometry", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> music = ContentArray.Where(x => (x.ToString().ToLower().Contains("music", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("instrument", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("musical", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("concert", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("instrumental", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> nursing = ContentArray.Where(x => (x.ToString().ToLower().Contains("nurse", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("nursing", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("healthcare", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("medicine") || x.ToString().ToLower().Contains("doctor", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("vaccine", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> performance = ContentArray.Where(x => (x.ToString().ToLower().Contains("performing arts", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("plays", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("operas", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("movie", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("actor", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("actress", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("stage", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> psych = ContentArray.Where(x => (x.ToString().ToLower().Contains("psych", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("therapy", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("counseling", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("mental health", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("adult child", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> physics = ContentArray.Where(x => (x.ToString().ToLower().Contains("physics", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("astronomy", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> politics = ContentArray.Where(x => (x.ToString().ToLower().Contains("politics", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("law", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("government", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("vet", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));
            IEnumerable<string> slim = ContentArray.Where(x => (x.ToString().ToLower().Contains("library", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("librarian", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("libraries", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("collection development", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("children", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("juvenile", StringComparison.CurrentCulture)) && !(x.ToString().ToLower().Contains("-- fiction", StringComparison.CurrentCulture) || x.ToString().ToLower().Contains("--fiction", StringComparison.CurrentCulture)));

            // Get all the rest of the subjects incase they need to be added to the existing lists and write them to a file
            IEnumerable<string> notCategorizedTopics = ContentArray
                .Except(art).Except(biology).Except(business).Except(chemistry).Except(computer)
                .Except(education).Except(fiction).Except(forensics).Except(geoscience).Except(history)
                .Except(hper).Except(humanities).Except(idt).Except(inter).Except(math).Except(music)
                .Except(nursing).Except(performance).Except(physics).Except(psych).Except(politics).Except(slim);

            // Write uncategorized topics
            File.WriteAllLines(uncategorizedOutputFile, notCategorizedTopics);

            // Generate Files for each topic to go into the list in EmailNewBooks
            // TODO: Get this to just update the actual code file
            File.WriteAllLines(Path.Combine(outputFolder, "ArtSubjects.txt"), art);
            File.WriteAllLines(Path.Combine(outputFolder, "BiologySubjects.txt"), biology);
            File.WriteAllLines(Path.Combine(outputFolder, "BusinessSubjects.txt"), business);
            File.WriteAllLines(Path.Combine(outputFolder, "ChemistrySubjects.txt"), chemistry);
            File.WriteAllLines(Path.Combine(outputFolder, "ComputerSubjects.txt"), computer);
            File.WriteAllLines(Path.Combine(outputFolder, "EducationSubjects.txt"), education);
            File.WriteAllLines(Path.Combine(outputFolder, "FictionSubjects.txt"), fiction);
            File.WriteAllLines(Path.Combine(outputFolder, "ForensicsSubjects.txt"), forensics);
            File.WriteAllLines(Path.Combine(outputFolder, "GeoscienceSubjects.txt"), geoscience);
            File.WriteAllLines(Path.Combine(outputFolder, "HistorySubjects.txt"), history);
            File.WriteAllLines(Path.Combine(outputFolder, "HPERSubjects.txt"), hper);
            File.WriteAllLines(Path.Combine(outputFolder, "HumanitiesSubjects.txt"), humanities);
            File.WriteAllLines(Path.Combine(outputFolder, "IDTSubjects.txt"), idt);
            File.WriteAllLines(Path.Combine(outputFolder, "InterDisSubjects.txt"), inter);
            File.WriteAllLines(Path.Combine(outputFolder, "MathSubjects.txt"), math);
            File.WriteAllLines(Path.Combine(outputFolder, "MusicSubjects.txt"), music);
            File.WriteAllLines(Path.Combine(outputFolder, "NursingSubjects.txt"), nursing);
            File.WriteAllLines(Path.Combine(outputFolder, "PerformanceSubjects.txt"), performance);
            File.WriteAllLines(Path.Combine(outputFolder, "PhysicsSubjects.txt"), physics);
            File.WriteAllLines(Path.Combine(outputFolder, "PsychSubjects.txt"), psych);
            File.WriteAllLines(Path.Combine(outputFolder, "PoliticsSubjects.txt"), politics);
            File.WriteAllLines(Path.Combine(outputFolder, "SlimSubjects.txt"), slim);
        }
    }
}
